# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{merlin_gateway}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Inge Jørgensen"]
  s.date = %q{2011-06-09}
  s.description = %q{Client for the Aspiro Merlin SMS gateway}
  s.email = %q{inge@manualdesign.no.no}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/merlin_gateway.rb",
    "lib/merlin_gateway/client.rb",
    "lib/merlin_gateway/sms_message.rb",
    "merlin_gateway.gemspec",
    "test/helper.rb",
    "test/test_merlin_gateway.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Client for the Aspiro Merlin SMS gateway}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<builder>, [">= 2.1.2"])
      s.add_runtime_dependency(%q<typhoeus>, [">= 0.2.0"])
    else
      s.add_dependency(%q<builder>, [">= 2.1.2"])
      s.add_dependency(%q<typhoeus>, [">= 0.2.0"])
    end
  else
    s.add_dependency(%q<builder>, [">= 2.1.2"])
    s.add_dependency(%q<typhoeus>, [">= 0.2.0"])
  end
end

